/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
if !(isServer) exitWith {};

#include "functions.sqf"
#include "config.sqf"
#include "classes.sqf"
#include "blackLists.sqf"


// L_ambiCivs_mainArray   = [];
L_ambiCivs_nextSpawn	= 0.5;
L_ambiCivs_currentCivs	= 0;
L_ambiCivs_civs = [];
L_ambiCivs_players = [];


L_ambiCivs_debugMarkerIndex = 1;
L_ambiCivs_debugMarkers = [];


[{
	call L_ambiCivs_fnc_spawnManager;
}, 0.25] call CBA_fnc_addPerFrameHandler;
/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
